### PR TITLE
Added file output for timing measures

### PR DESCRIPTION
**Pull request by Pamoi**

### CODE REVIEW

**Comment by lbarman** [comment]
Couldn't this be done via " | tee grep timing.txt" ?

**Comment by Pamoi** [comment]
Sure it could but I planned to do a small python script to generate plots for the measures and found it easier to just read from a file. The previous behavior is still available by changing the `OutputInterface` in `timing.go`.

**Comment by lbarman** [comment]
OK, sure. Can you add "timing.txt" or whatever the output is to .gitignore then please?

**Comment by lbarman** [comment]
(done)

**Pull request merged**
